Adds vectorized time integration to pyoptmat
Argonne-National-Laboratory/pyoptmat pull request #23
Opened 2023-03-03 02:18 UTC by reverendbedford

Vectorizes time integration by chunking multiple time steps.

2023-03-06 17:00 UTC, tianjuchen commented
I think we don't need chunk-time-sized temperature dependent scaling of the model parameters. I removed the chunk size in piecewise scaling function, which is working fine on my toy example.

2023-03-17 19:21 UTC, tianjuchen requested changes

2023-03-17 19:21 UTC, tianjuchen commented on examples/structural-inference/tension-temperature/infer.py
wrong parameters names

2023-03-17 19:21 UTC, tianjuchen commented on examples/structural-inference/tension-temperature/infer.py
> +    names = ["n", "eta", "theta", "tau"]
names = ["n_vals", "eta_vals", "theta_vals", "tau_vals"]

2023-03-17 19:21 UTC, tianjuchen commented on pyoptmat/temperature.py
I guess all the temperature scaling function need to be adjusted if temperature varies as time.

2023-03-29 17:33 UTC, reverendbedford commented on examples/structural-inference/tension-temperature/infer.py
These don't have to match the actual parameter names -- they are just for output.

2023-03-29 17:33 UTC, reverendbedford commented on pyoptmat/temperature.py
They all should work for the temperature-dependent case now.

2023-03-31 20:47 UTC, merged